spring.application.name=auth-service
server.port=4005

# Actuator + Prometheus monitoring
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
